<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<title>ixi</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<link href="style1.css" rel="stylesheet" type="text/css">
<?PHP
	$pag =''; 	//init var
	function f_style($link){
		if ($pag != $link){
			return "normal";
		}else{
			return "current";
		}	
	}
?>

</head>



<body>

<div id="logo"> 
  		<a href="www.ixi-software.net"><img src="images/ixi_logo.gif" width="44" height="28" border="0"></a> 
</div>
